# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bee1a62d18dda54a06cf50a64e1daad345572e4593e26134ebf9544f9923126ee9d616a41b0431f67d744396aaf2077506eb96fe0f83887ff48fd86ae7d4c6cc

test:
  secret_key_base: 1c23339e7e83ca530058a77dd6227185b9fdd3e5150c3a6f8a2e00187241d21044a4f0af87af81935777dfdd552e186fa742b179654cdce6665231e2a8e64ea2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
